
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action EditAction;
	
	private global::Gtk.Action OpenAction;
	
	private global::Gtk.Action FileAction1;
	
	private global::Gtk.Action OpenAction1;
	
	private global::Gtk.Action EditAction1;
	
	private global::Gtk.Action FileAction2;
	
	private global::Gtk.Action OpenAction2;
	
	private global::Gtk.Action CheckAction;
	
	private global::Gtk.Action Action;
	
	private global::Gtk.Action SaveAction;
	
	private global::Gtk.Action SaveAsAction;
	
	private global::Gtk.Action Action1;
	
	private global::Gtk.Action ExitAction;
	
	private global::Gtk.Action EditAction2;
	
	private global::Gtk.Action ViewAction;
	
	private global::Gtk.Action OptionsAction;
	
	private global::Gtk.Action HelpAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar2;
	
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.Fixed fixed7;
	
	private global::Gtk.HPaned hpaned1;
	
	private global::Gtk.Notebook notebook1;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView textview3;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Notebook notebook2;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.TextView textview5;
	
	private global::Gtk.Label label2;
	
	private global::Stetic.Custom custom1;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Fixed fixed8;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	
	private global::Gtk.TextView textview11;
	
	private global::Gtk.Fixed fixed2;
	
	private global::Gtk.Statusbar statusbar2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
		w1.Add (this.EditAction, null);
		this.OpenAction = new global::Gtk.Action ("OpenAction", global::Mono.Unix.Catalog.GetString ("Open"), null, null);
		this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.OpenAction, null);
		this.FileAction1 = new global::Gtk.Action ("FileAction1", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction1, null);
		this.OpenAction1 = new global::Gtk.Action ("OpenAction1", global::Mono.Unix.Catalog.GetString ("Open"), null, null);
		this.OpenAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.OpenAction1, null);
		this.EditAction1 = new global::Gtk.Action ("EditAction1", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
		this.EditAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
		w1.Add (this.EditAction1, null);
		this.FileAction2 = new global::Gtk.Action ("FileAction2", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction2.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction2, null);
		this.OpenAction2 = new global::Gtk.Action ("OpenAction2", global::Mono.Unix.Catalog.GetString ("Open"), null, null);
		this.OpenAction2.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.OpenAction2, null);
		this.CheckAction = new global::Gtk.Action ("CheckAction", global::Mono.Unix.Catalog.GetString ("Check"), null, null);
		this.CheckAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Check");
		w1.Add (this.CheckAction, null);
		this.Action = new global::Gtk.Action ("Action", global::Mono.Unix.Catalog.GetString ("-"), null, null);
		this.Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("-");
		w1.Add (this.Action, null);
		this.SaveAction = new global::Gtk.Action ("SaveAction", global::Mono.Unix.Catalog.GetString ("Save"), null, null);
		this.SaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.SaveAction, null);
		this.SaveAsAction = new global::Gtk.Action ("SaveAsAction", global::Mono.Unix.Catalog.GetString ("Save as"), null, null);
		this.SaveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save as");
		w1.Add (this.SaveAsAction, null);
		this.Action1 = new global::Gtk.Action ("Action1", global::Mono.Unix.Catalog.GetString ("-"), null, null);
		this.Action1.ShortLabel = global::Mono.Unix.Catalog.GetString ("-");
		w1.Add (this.Action1, null);
		this.ExitAction = new global::Gtk.Action ("ExitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.ExitAction, null);
		this.EditAction2 = new global::Gtk.Action ("EditAction2", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
		this.EditAction2.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
		w1.Add (this.EditAction2, null);
		this.ViewAction = new global::Gtk.Action ("ViewAction", global::Mono.Unix.Catalog.GetString ("View"), null, null);
		this.ViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("View");
		w1.Add (this.ViewAction, null);
		this.OptionsAction = new global::Gtk.Action ("OptionsAction", global::Mono.Unix.Catalog.GetString ("Options"), null, null);
		this.OptionsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Options");
		w1.Add (this.OptionsAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString (@"<ui><menubar name='menubar2'><menu name='FileAction2' action='FileAction2'><menuitem name='OpenAction2' action='OpenAction2'/><menuitem name='CheckAction' action='CheckAction'/><menuitem name='Action' action='Action'/><menuitem name='SaveAction' action='SaveAction'/><menuitem name='SaveAsAction' action='SaveAsAction'/><menuitem name='Action1' action='Action1'/><menuitem name='ExitAction' action='ExitAction'/></menu><menu name='EditAction2' action='EditAction2'/><menu name='ViewAction' action='ViewAction'/><menu name='OptionsAction' action='OptionsAction'/><menu name='HelpAction' action='HelpAction'/></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox1.Add (this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.vbox1.Add (this.fixed1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.fixed1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.fixed7 = new global::Gtk.Fixed ();
		this.fixed7.Name = "fixed7";
		this.fixed7.HasWindow = false;
		this.vbox3.Add (this.fixed7);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fixed7]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 132;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview3 = new global::Gtk.TextView ();
		this.textview3.CanFocus = true;
		this.textview3.Name = "textview3";
		this.GtkScrolledWindow.Add (this.textview3);
		this.notebook1.Add (this.GtkScrolledWindow);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Functions");
		this.notebook1.SetTabLabel (this.GtkScrolledWindow, this.label1);
		this.label1.ShowAll ();
		// Notebook tab
		global::Gtk.Label w7 = new global::Gtk.Label ();
		w7.Visible = true;
		this.notebook1.Add (w7);
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Variables");
		this.notebook1.SetTabLabel (w7, this.label5);
		this.label5.ShowAll ();
		this.hpaned1.Add (this.notebook1);
		global::Gtk.Paned.PanedChild w8 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.notebook1]));
		w8.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.notebook2 = new global::Gtk.Notebook ();
		this.notebook2.CanFocus = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 0;
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textview5 = new global::Gtk.TextView ();
		this.textview5.CanFocus = true;
		this.textview5.Name = "textview5";
		this.GtkScrolledWindow1.Add (this.textview5);
		this.notebook2.Add (this.GtkScrolledWindow1);
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("page1");
		this.notebook2.SetTabLabel (this.GtkScrolledWindow1, this.label2);
		this.label2.ShowAll ();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.custom1 = new global::Stetic.Custom ();
		this.custom1.Name = "custom1";
		this.custom1.Int1 = 0;
		this.custom1.Int2 = 0;
		this.notebook2.Add (this.custom1);
		global::Gtk.Notebook.NotebookChild w11 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.custom1]));
		w11.Position = 1;
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("page2");
		this.notebook2.SetTabLabel (this.custom1, this.label3);
		this.label3.ShowAll ();
		// Notebook tab
		global::Gtk.Label w12 = new global::Gtk.Label ();
		w12.Visible = true;
		this.notebook2.Add (w12);
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("page3");
		this.notebook2.SetTabLabel (w12, this.label4);
		this.label4.ShowAll ();
		this.hpaned1.Add (this.notebook2);
		this.vbox3.Add (this.hpaned1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hpaned1]));
		w14.Position = 1;
		// Container child vbox3.Gtk.Box+BoxChild
		this.fixed8 = new global::Gtk.Fixed ();
		this.fixed8.Name = "fixed8";
		this.fixed8.HasWindow = false;
		this.vbox3.Add (this.fixed8);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fixed8]));
		w15.Position = 2;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.textview11 = new global::Gtk.TextView ();
		this.textview11.CanFocus = true;
		this.textview11.Name = "textview11";
		this.GtkScrolledWindow2.Add (this.textview11);
		this.vbox3.Add (this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow2]));
		w17.Position = 3;
		w17.Expand = false;
		w17.Fill = false;
		this.vbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox3]));
		w18.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.vbox1.Add (this.fixed2);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.fixed2]));
		w19.Position = 3;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar2 = new global::Gtk.Statusbar ();
		this.statusbar2.Name = "statusbar2";
		this.statusbar2.Spacing = 6;
		this.vbox1.Add (this.statusbar2);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar2]));
		w20.Position = 4;
		w20.Expand = false;
		w20.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 656;
		this.DefaultHeight = 338;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
